spring:
  data:
    mongodb:
      #      mongodb://<user>:<passwd>@<host>:<port>/<dbname>
      uri:  mongodb+srv://dharbar:${MONGO_DB_PASS}@musictags-tgemi.gcp.mongodb.net/music?retryWrites=true&w=majority

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
