springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-ui

management:
  endpoints:
    web:
      exposure:
        include: "*"

itunes:
  token:
    admin:
      private-key: ${ITUNES_PRIVATE_KEY}
      api-key-id: ${ITUNES_API_KEY}
      issuer-id: ${ITUNES_ISSUER_ID}

logging.level.org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
